[package]
name = "wheel-3box"
version = "0.1.31"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
ceramic-config = { path = "../ceramic-config", version = "0.1.32" }
clap = { version = "4.1.4", features = ["derive"] }
did-method-key = "0.2"
env_logger = "0.10.0"
futures-util = "0.3.26"
hex = "0.4.3"
inquire = "0.5.3"
log = "0.4"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls", "stream"] }
semver = "1.0.16"
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls", "sqlite"] }
ssi = "0.5.0"
tokio = { version = "1.25.0", default-features = false, features = ["fs", "macros", "process", "rt", "rt-multi-thread"] }
which = "4.4.0"

[[bin]]
name = "wheel"
path = "src/main.rs"
